categories:
    path: /categories
    methods: [GET]
    controller: App\Controller\CategoryController::getAllCategories

category:
  path: /categories/{id}
  methods: [GET]
  controller: App\Controller\CategoryController::getCategory

category_delete:
  path: /categories/{id}
  methods: [DELETE]
  controller: App\Controller\CategoryController::deleteCategory