categories:
    path: /categories
    methods: [GET]
    controller: App\Controller\CategoryController::getAllCategories

categories #TODO:
  path: /categories
  methods: [POST]
  controller: App\Controller\CategoryController::#TODO

category:
  path: /categories/{id}
  methods: [GET]
  controller: App\Controller\CategoryController::getCategory

category_delete:
  path: /categories/{id}
  methods: [DELETE]
  controller: App\Controller\CategoryController::deleteCategory

category #TODO:
  path: /categories/{id}
  methods: [PUT]
  controller: App\Controller\CategoryController::#TODO

films:
  path: /films
  methods: [GET]
  controller: App\Controller\FilmController::getAllFilms

films #TODO:
  path: /films
  methods: [POST]
  controller: App\Controller\FilmController::#TODO

film:
  path: /films/{id}
  methods: [GET]
  controller: App\Controller\FilmController::getFilm

film #TODO:
  path: /films/{id}
  methods: [PUT]
  controller: App\Controller\FilmController::#TODO

film_delete:
  path: /films/{id}
  methods: [DELETE]
  controller: App\Controller\FilmController::deleteFilm

acteurs:
  path: /acteurs
  methods: [GET]
  controller: App\Controller\ActeurController::getAllActeurs

acteurs #TODO:
  path: /acteurs
  methods: [POST]
  controller: App\Controller\ActeurController::#TODO

acteur:
  path: /acteurs/{id}
  methods: [GET]
  controller: App\Controller\ActeurController::getActeur

acteur_delete:
  path: /acteurs/{id}
  methods: [DELETE]
  controller: App\Controller\ActeurController::deleteActeur

acteur #TODO:
  path: /acteurs/{id}
  methods: [PUT]
  controller: App\Controller\ActeurController::#TODO