home:
  path: /home
  controller: App\Controller\HomeController::getHome

categories:
  path: /categories
  methods: [GET]
  controller: App\Controller\CategoryController::getAllCategories

categories_add:
  path: /categories
  methods: [POST]
  controller: App\Controller\CategoryController::createCategory

category:
  path: /categories/{id}
  methods: [GET]
  controller: App\Controller\CategoryController::getCategory

category_delete:
  path: /categories/{id}
  methods: [DELETE]
  controller: App\Controller\CategoryController::deleteCategory

category_update:
  path: /categories/{id}
  methods: [PUT]
  controller: App\Controller\CategoryController::updateCategory

films:
  path: /films
  methods: [GET]
  controller: App\Controller\FilmController::getAllFilms

films_add:
  path: /films
  methods: [POST]
  controller: App\Controller\FilmController::createFilm

film:
  path: /films/{id}
  methods: [GET]
  controller: App\Controller\FilmController::getFilm

film_update:
  path: /films/{id}
  methods: [PUT]
  controller: App\Controller\FilmController::updateFilm

film_delete:
  path: /films/{id}
  methods: [DELETE]
  controller: App\Controller\FilmController::deleteFilm

acteurs:
  path: /acteurs
  methods: [GET]
  controller: App\Controller\ActeurController::getAllActeurs

acteurs_add:
  path: /acteurs
  methods: [POST]
  controller: App\Controller\ActeurController::createActeur

acteur:
  path: /acteurs/{id}
  methods: [GET]
  controller: App\Controller\ActeurController::getActeur

acteur_delete:
  path: /acteurs/{id}
  methods: [DELETE]
  controller: App\Controller\ActeurController::deleteActeur

acteur_update:
  path: /acteurs/{id}
  methods: [PUT]
  controller: App\Controller\ActeurController::updateActeur